# Generated by Django 5.2.8 on 2026-05-20 21:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estacionamiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infraccion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
