# Generated by Django 5.2.8 on 2026-05-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estacionamiento', '0002_infraccion_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='apellido',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='saldo_operativo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
