# Generated by Django 5.2.8 on 2026-05-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estacionamiento', '0006_cierrecaja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocaja',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='tipo',
            field=models.CharField(max_length=10),
        ),
    ]
