# Generated by Django 5.2.8 on 2026-05-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estacionamiento', '0007_alter_movimientocaja_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infraccion',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='infraccion',
            name='qr_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
