# Generated by Django 5.2.8 on 2026-05-28 00:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estacionamiento', '0008_infraccion_monto_infraccion_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierrecaja',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
