# Generated by Django 5.2.8 on 2026-05-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estacionamiento', '0009_alter_cierrecaja_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='cerrado',
            field=models.BooleanField(default=False),
        ),
    ]
