# Generated by Django 5.2.8 on 2026-05-28 18:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estacionamiento', '0010_movimientocaja_cerrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrecaja',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
