# Generated by Django 5.2.8 on 2026-05-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estacionamiento', '0011_cierrecaja_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierrecaja',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
