# Generated by Django 5.2.8 on 2026-05-28 19:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estacionamiento', '0012_alter_cierrecaja_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cierrecaja',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='cierrecaja',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='cierrecaja',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='cantidad_movimientos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='fecha_apertura',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
