# Generated by Django 5.2.8 on 2026-06-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estacionamiento', '0013_remove_cierrecaja_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='exento_parcial',
            field=models.BooleanField(default=False),
        ),
    ]
