# Generated by Django 5.2.8 on 2026-06-02 19:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estacionamiento', '0014_vehiculo_exento_parcial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cierrecaja',
            name='fecha_cierre',
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
