# Generated by Django 5.2.8 on 2026-06-02 20:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estacionamiento', '0015_remove_cierrecaja_fecha_cierre_cierrecaja_creado_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrecaja',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='fecha_cierre',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
