# Generated by Django 5.2.8 on 2026-06-02 21:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estacionamiento', '0016_cierrecaja_creado_por_cierrecaja_fecha_cierre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
