# Generated by Django 5.2.8 on 2026-06-02 22:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estacionamiento', '0017_movimientocaja_creado_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='infraccion',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
