# Generated by Django 5.2.8 on 2026-06-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estacionamiento', '0018_infraccion_creado_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infraccion',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
