# Generated by Django 5.2.8 on 2026-06-03 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estacionamiento', '0019_alter_infraccion_creado_en'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estacionamiento',
            old_name='costo',
            new_name='costo_base',
        ),
        migrations.RemoveField(
            model_name='estacionamiento',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='estacionamiento',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='estacionamiento',
            name='registrado_por',
        ),
        migrations.AddField(
            model_name='estacionamiento',
            name='costo_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='estacionamiento',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='estacionamiento',
            name='duracion_min',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='estacionamiento',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('FINALIZADO', 'Finalizado')], default='ACTIVO', max_length=20),
        ),
        migrations.AddField(
            model_name='estacionamiento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estacionamientos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='hora_inicio',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='subcuadra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_estacionamiento.subcuadra'),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
