# Generated by Django 5.2.8 on 2026-06-03 20:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estacionamiento', '0020_rename_costo_estacionamiento_costo_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificacioninspector',
            name='infraccion_generada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
