# Generated by Django 5.2.8 on 2026-06-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estacionamiento', '0021_verificacioninspector_infraccion_generada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infraccion',
            name='cancelada',
        ),
        migrations.AddField(
            model_name='infraccion',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
