# Generated by Django 5.2.8 on 2026-06-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estacionamiento', '0022_remove_infraccion_cancelada_infraccion_fecha_pago'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='estacionamiento',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ACTIVO')), fields=('vehiculo',), name='unique_estacionamiento_activo_por_vehiculo'),
        ),
    ]
