# Generated by Django 5.2.8 on 2026-06-08 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estacionamiento', '0023_estacionamiento_unique_estacionamiento_activo_por_vehiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infraccion',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='infraccion',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='infraccion',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='movimientocaja',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 6, 8, 11, 48, 20, 226189, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
