from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("app_estacionamiento", "0034_usuario_campos_contacto")]
    operations = [
        migrations.AddField(model_name="usuario", name="es_tesorero",
            field=models.BooleanField(default=False)),
        migrations.AddField(model_name="municipio", name="comision_vendedor",
            field=models.DecimalField(decimal_places=2, default=7, max_digits=5,
                verbose_name="Comisión vendedor (%)")),
        migrations.AddField(model_name="municipio", name="tolerancia_multa_minutos",
            field=models.IntegerField(default=5, verbose_name="Tolerancia multa (min)")),
        migrations.AddField(model_name="vehiculo", name="tipo",
            field=models.CharField(choices=[("auto","Auto"),("moto","Moto")],
                default="auto", max_length=10, verbose_name="Tipo de vehículo")),
        migrations.AddField(model_name="tarifa", name="precio_por_hora_moto",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6,
                verbose_name="Precio/hora moto")),
        migrations.AddField(model_name="tarifa", name="precio_abono_auto",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10,
                verbose_name="Precio abono mensual (auto)")),
        migrations.AddField(model_name="tarifa", name="precio_abono_moto",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10,
                verbose_name="Precio abono mensual (moto)")),
        migrations.AddField(model_name="movimientocaja", name="medio_pago",
            field=models.CharField(choices=[("efectivo","Efectivo"),("mercadopago","MercadoPago")],
                default="efectivo", max_length=20, verbose_name="Medio de pago")),
        migrations.AddField(model_name="movimientocaja", name="comision_monto",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10,
                verbose_name="Comisión generada")),
        migrations.CreateModel(name="AbonoMensual", fields=[
            ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("mes", models.DateField(verbose_name="Mes del abono")),
            ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
            ("medio_pago", models.CharField(choices=[("efectivo","Efectivo"),("mercadopago","MercadoPago")],
                default="efectivo", max_length=20)),
            ("creado_en", models.DateTimeField(auto_now_add=True)),
            ("municipio", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                related_name="abonos", to="app_estacionamiento.municipio")),
            ("vehiculo", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                related_name="abonos", to="app_estacionamiento.vehiculo")),
            ("vendedor", models.ForeignKey(blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="abonos_cobrados", to=settings.AUTH_USER_MODEL)),
            ("conductor", models.ForeignKey(blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="abonos_contratados", to=settings.AUTH_USER_MODEL)),
            ("movimiento_caja", models.ForeignKey(blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app_estacionamiento.movimientocaja")),
        ], options={"verbose_name":"Abono mensual","verbose_name_plural":"Abonos mensuales","ordering":["-mes"]}),
        migrations.AddConstraint(model_name="abonomensual",
            constraint=models.UniqueConstraint(
                fields=["vehiculo","municipio","mes"],
                name="unique_abono_vehiculo_municipio_mes")),
        migrations.CreateModel(name="Rendicion", fields=[
            ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("periodo", models.CharField(choices=[("diario","Diario"),("semanal","Semanal"),("mensual","Mensual")], max_length=10)),
            ("fecha_desde", models.DateField()),
            ("fecha_hasta", models.DateField()),
            ("total_efectivo",   models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ("total_digital",    models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ("total_comisiones", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ("total_neto",       models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ("estado", models.CharField(choices=[("pendiente","Pendiente de validación"),("validada","Validada por tesorería"),("observada","Con observaciones")], default="pendiente", max_length=15)),
            ("notas_tesorero", models.TextField(blank=True)),
            ("creado_en",   models.DateTimeField(auto_now_add=True)),
            ("validado_en", models.DateTimeField(blank=True, null=True)),
            ("municipio", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                related_name="rendiciones", to="app_estacionamiento.municipio")),
            ("admin", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                related_name="rendiciones_generadas", to=settings.AUTH_USER_MODEL)),
            ("tesorero", models.ForeignKey(blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rendiciones_validadas", to=settings.AUTH_USER_MODEL)),
        ], options={"verbose_name":"Rendición","verbose_name_plural":"Rendiciones","ordering":["-creado_en"]}),
        migrations.CreateModel(name="LiquidacionComision", fields=[
            ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("fecha_desde",  models.DateField()),
            ("fecha_hasta",  models.DateField()),
            ("monto_total",  models.DecimalField(decimal_places=2, max_digits=12)),
            ("estado", models.CharField(choices=[("pendiente","Pendiente de depósito"),("depositada","Depositada por tesorería"),("certificada","Certificada por el vendedor")], default="pendiente", max_length=15)),
            ("depositada_en",  models.DateTimeField(blank=True, null=True)),
            ("notas_tesorero", models.TextField(blank=True)),
            ("certificada_en", models.DateTimeField(blank=True, null=True)),
            ("creado_en",      models.DateTimeField(auto_now_add=True)),
            ("vendedor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                related_name="liquidaciones_comision", to=settings.AUTH_USER_MODEL)),
            ("municipio", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                to="app_estacionamiento.municipio")),
            ("rendicion", models.ForeignKey(blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="liquidaciones", to="app_estacionamiento.rendicion")),
            ("depositada_por", models.ForeignKey(blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="liquidaciones_depositadas", to=settings.AUTH_USER_MODEL)),
        ], options={"verbose_name":"Liquidación de comisión","verbose_name_plural":"Liquidaciones de comisión","ordering":["-creado_en"]}),
    ]
