# Generated by Django 5.2.8 on 2026-07-29 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estacionamiento', '0044_estacionamiento_duracion_horas_decimal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloMunicipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('ocupacion_tiempo_real', 'Ocupación en tiempo real'), ('reportes_comparativos', 'Reportes comparativos'), ('balance_por_dominio', 'Balance por dominio'), ('areas_reservadas', 'Áreas reservadas'), ('geolocalizacion_inspector', 'Geolocalización del inspector'), ('notificaciones_conductor', 'Notificaciones al conductor'), ('informes_automaticos', 'Informes automáticos programados')], max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('precio_mensual', models.DecimalField(decimal_places=2, default=0, help_text='Precio mensual en pesos que el municipio paga por este módulo.', max_digits=10)),
                ('activado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Módulo de municipio',
                'verbose_name_plural': 'Módulos de municipios',
            },
        ),
        migrations.RemoveConstraint(
            model_name='abonomensual',
            name='unique_abono_vehiculo_municipio_mes',
        ),
        migrations.RemoveConstraint(
            model_name='destinatarioinforme',
            name='unique_destinatario_municipio',
        ),
        migrations.AddField(
            model_name='usuario',
            name='es_superadmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='abonomensual',
            name='conductor',
            field=models.ForeignKey(blank=True, help_text='Conductor que contrató el abono (null si lo cargó el vendedor sin usuario).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonos_contratados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='abonomensual',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='abonomensual',
            name='vendedor',
            field=models.ForeignKey(blank=True, help_text='Vendedor/kiosco que cobró el abono (null si fue digital).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonos_cobrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cierrecaja',
            name='certificado',
            field=models.BooleanField(default=False, help_text='El admin auditó y certificó este cierre.'),
        ),
        migrations.AlterField(
            model_name='cierrecaja',
            name='certificado_en',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el admin certificó el cierre.', null=True),
        ),
        migrations.AlterField(
            model_name='cierrecaja',
            name='certificado_por',
            field=models.ForeignKey(blank=True, help_text='Admin que certificó el cierre.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_certificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='liquidacioncomision',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liquidacioncomision',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, help_text='Suma de comisiones del período.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='liquidacioncomision',
            name='rendicion',
            field=models.ForeignKey(blank=True, help_text='Rendición que originó esta liquidación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidaciones', to='app_estacionamiento.rendicion'),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='comision_monto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto que retiene el vendedor como comisión en este movimiento.', max_digits=10, verbose_name='Comisión generada'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='comision_vendedor',
            field=models.DecimalField(decimal_places=2, default=7, help_text='Porcentaje que retiene el vendedor de cada cobro.', max_digits=5, verbose_name='Comisión vendedor (%)'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='logo',
            field=models.ImageField(blank=True, help_text='Imagen PNG/SVG con fondo transparente. Altura recomendada: 80px.', null=True, upload_to='municipios/logos/', verbose_name='Logo del municipio'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='tolerancia_multa_minutos',
            field=models.IntegerField(default=5, help_text='Minutos de gracia: si el conductor paga la multa dentro de este plazo, se cancela automáticamente.', verbose_name='Tolerancia multa (min)'),
        ),
        migrations.AlterField(
            model_name='rendicion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rendicion',
            name='notas_tesorero',
            field=models.TextField(blank=True, verbose_name='Observaciones del tesorero'),
        ),
        migrations.AlterField(
            model_name='rendicion',
            name='total_neto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total a rendir = efectivo + digital - comisiones.', max_digits=12),
        ),
        migrations.AlterUniqueTogether(
            name='abonomensual',
            unique_together={('vehiculo', 'municipio', 'mes')},
        ),
        migrations.AlterUniqueTogether(
            name='destinatarioinforme',
            unique_together={('municipio', 'correo')},
        ),
        migrations.AddField(
            model_name='modulomunicipio',
            name='activado_por',
            field=models.ForeignKey(blank=True, help_text='Superadmin que activó este módulo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modulos_activados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modulomunicipio',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='app_estacionamiento.municipio'),
        ),
        migrations.AlterUniqueTogether(
            name='modulomunicipio',
            unique_together={('municipio', 'modulo')},
        ),
    ]
