# Generated by Django 5.2.8 on 2026-08-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estacionamiento', '0050_vehiculo_vigencia_exencion_verificada'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='plantilladocumento',
            name='unique_plantilla_municipio_tipo',
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='mp_payment_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ID de pago MercadoPago'),
        ),
        migrations.AlterField(
            model_name='plantilladocumento',
            name='cuerpo',
            field=models.TextField(blank=True, help_text='Texto principal del comprobante. Podés usar variables.', verbose_name='Cuerpo / base legal'),
        ),
        migrations.AlterField(
            model_name='plantilladocumento',
            name='encabezado',
            field=models.TextField(blank=True, help_text='Texto que aparece arriba del comprobante. Podés usar variables.', verbose_name='Encabezado'),
        ),
        migrations.AlterField(
            model_name='plantilladocumento',
            name='pie',
            field=models.TextField(blank=True, help_text='Texto que aparece al pie. Podés usar variables.', verbose_name='Pie / instrucciones'),
        ),
        migrations.AlterField(
            model_name='rendicion',
            name='total_efectivo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Suma del efectivo de todos los cierres incluidos.', max_digits=12),
        ),
        migrations.AlterUniqueTogether(
            name='plantilladocumento',
            unique_together={('municipio', 'tipo')},
        ),
    ]
