# Generated by Django 5.2.8 on 2026-08-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estacionamiento', '0052_merge_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='monto_maximo_carga',
            field=models.PositiveIntegerField(default=50000, help_text='Monto máximo que puede cargar un conductor via MercadoPago en una sola operación.', verbose_name='Monto máximo de carga MP ($)'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='monto_minimo_carga',
            field=models.PositiveIntegerField(default=500, help_text='Monto mínimo que puede cargar un conductor via MercadoPago.', verbose_name='Monto mínimo de carga MP ($)'),
        ),
    ]
