# Generated by Django 5.2.8 on 2026-08-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estacionamiento', '0054_infraccion_sia_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='minutos_entre_infracciones',
            field=models.PositiveIntegerField(default=15, help_text='Tiempo mínimo antes de poder infraccionar de nuevo al mismo vehículo. Defecto: 15 min.', verbose_name='Minutos entre infracciones (mismo vehículo)'),
        ),
    ]
