# Generated by Django 5.2.8 on 2026-08-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estacionamiento', '0055_municipio_minutos_entre_infracciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='icono_app',
            field=models.ImageField(blank=True, help_text='PNG cuadrado, mínimo 192×192px. Aparece como ícono al instalar la PWA en el celular.', null=True, upload_to='municipios/iconos/', verbose_name='Ícono de la app (acceso directo)'),
        ),
    ]
