# Generated by Django 5.2.8 on 2026-08-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estacionamiento', '0056_municipio_icono_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='color_acento',
            field=models.CharField(blank=True, default='#bed630', help_text='Color de botones secundarios y highlights (ej: #bed630).', max_length=7, verbose_name='Color acento'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='color_secundario',
            field=models.CharField(default='#444444', help_text='Color del footer y textos de soporte (ej: #444444).', max_length=7, verbose_name='Color secundario'),
        ),
    ]
