# Generated by Django 5.2.8 on 2026-08-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estacionamiento', '0057_municipio_color_acento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='sia_nci',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='NCI verificación SIA'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='sia_titular_apellido',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Apellido titular SIA'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='sia_titular_dni',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='DNI titular SIA'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='sia_titular_nombre',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nombre titular SIA'),
        ),
    ]
