# Generated by Django 5.2.8 on 2026-09-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estacionamiento', '0071_municipio_segundos_pausa_doble_copia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacionplataforma',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liquidacionplataforma',
            name='notas_superadmin',
            field=models.TextField(blank=True, default='', verbose_name='Notas del superadmin'),
        ),
        migrations.AlterField(
            model_name='liquidacionplataforma',
            name='notas_tesorero',
            field=models.TextField(blank=True, default='', verbose_name='Notas del tesorero'),
        ),
        migrations.AlterField(
            model_name='liquidacionplataforma',
            name='recaudacion_base',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total recaudado por el municipio en el período (base para calcular el % variable).', max_digits=12, verbose_name='Recaudación del período'),
        ),
        migrations.AlterField(
            model_name='modulomunicipio',
            name='precio_mensual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio mensual fijo en pesos que el municipio paga por este módulo. Se suma a la cuota base.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='concepto_recaudacion',
            field=models.CharField(choices=[('cierre_caja', 'Total de cierres de caja (neto municipio)'), ('rendiciones', 'Solo rendiciones validadas'), ('manual', 'Monto ingresado manualmente')], default='cierre_caja', help_text='Qué dato del sistema se usa para calcular el porcentaje variable.', max_length=20, verbose_name='Base de cálculo para el porcentaje'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='cuota_mantenimiento_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto fijo mensual que el municipio paga por hosting y mantenimiento del sistema.', max_digits=10, null=True, verbose_name='Cuota mensual de mantenimiento ($)'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='dia_cierre_liquidacion',
            field=models.PositiveSmallIntegerField(default=1, help_text='Día del mes en que se cierra el período de liquidación (1-28).', verbose_name='Día de cierre de liquidación'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='estadisticas_inspectores_activo',
            field=models.BooleanField(default=True, help_text='Si está desactivado, el inspector no ve sus métricas en el panel (infracciones del día, etc.).', verbose_name='Mostrar estadísticas a inspectores'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='porcentaje_plataforma',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje que la plataforma retiene sobre la recaudación del período. Ej: 2.50 = 2,5%.', max_digits=5, null=True, verbose_name='Porcentaje sobre recaudación (%)'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='token_tv',
            field=models.CharField(blank=True, default='', help_text='Token de solo lectura para la pantalla pública /tv/<token>/. Vacío = desactivado.', max_length=64, verbose_name='Token de dashboard TV'),
        ),
    ]
