# Generated by Django 5.2.8 on 2026-09-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estacionamiento', '0077_mapa_zonas_campos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='inspector_ve_sus_infracciones',
            field=models.BooleanField(default=False, help_text='Si está activado, el inspector puede ver en su panel las infracciones que él mismo labrό. Por defecto desactivado: el inspector solo carga infracciones, el admin las gestiona.', verbose_name='Inspector ve sus propias infracciones'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='sede_lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitud de la oficina o sede del administrador. Se muestra en el mapa de zonas.', max_digits=9, null=True, verbose_name='Latitud sede municipal'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='sede_lon',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitud de la oficina o sede del administrador. Se muestra en el mapa de zonas.', max_digits=9, null=True, verbose_name='Longitud sede municipal'),
        ),
        migrations.AlterField(
            model_name='subcuadra',
            name='tipo_zona',
            field=models.CharField(choices=[('pagado', 'Zona pagada'), ('libre', 'Zona libre')], default='pagado', help_text='Pagado = estacionamiento medido. Libre = sin cobro (zona céntrica liberada u otra).', max_length=10, verbose_name='Tipo de zona'),
        ),
    ]
