# Generated by Django 5.2.8 on 2026-09-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estacionamiento', '0082_municipio_descuento_verificados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='descuento_solo_vecinos',
            field=models.BooleanField(default=False, help_text="Si está activo, el descuento solo aplica a conductores verificados que además tengan 'Residente verificado' (es_residente_verificado=True). Si está inactivo, aplica a todos los conductores verificados.", verbose_name='Solo vecinos del municipio'),
        ),
        migrations.AddIndex(
            model_name='cierrecaja',
            index=models.Index(fields=['usuario', 'certificado'], name='idx_cierre_usuario_certificado'),
        ),
        migrations.AddIndex(
            model_name='cierrecaja',
            index=models.Index(fields=['usuario', 'certificado', 'rendicion'], name='idx_cierre_cert_rendicion'),
        ),
        migrations.AddIndex(
            model_name='infraccion',
            index=models.Index(fields=['municipio', 'creado_en'], name='idx_infraccion_municipio_fecha'),
        ),
        migrations.AddIndex(
            model_name='infraccion',
            index=models.Index(fields=['vehiculo', 'estado'], name='idx_infraccion_vehiculo_estado'),
        ),
        migrations.AddIndex(
            model_name='infraccion',
            index=models.Index(fields=['inspector', 'creado_en'], name='idx_infraccion_inspector_fecha'),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['usuario', 'cerrado', 'creado_en'], name='idx_movcaja_cerrado_fecha'),
        ),
    ]
