# Generated by Django 5.2.8 on 2026-09-24 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_estacionamiento', '0092_tarifa_duracion_minima_minutos'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='billeteraconductor',
            name='unique_billetera_conductor_municipio',
        ),
        migrations.AlterUniqueTogether(
            name='billeteraconductor',
            unique_together={('conductor', 'municipio')},
        ),
    ]
