# Generated by Django 5.2.8 on 2026-09-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estacionamiento', '0093_remove_billeteraconductor_unique_billetera_conductor_municipio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nombre_negocio',
            field=models.CharField(blank=True, default='', help_text='Ej: Kiosco Don Juan, Farmacia Central', max_length=200, verbose_name='Nombre del negocio / punto de venta'),
        ),
    ]
