# Generated by Django 5.2.8 on 2026-10-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estacionamiento', '0101_solicitud_eliminacion_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcuadra',
            name='calles_entre',
            field=models.CharField(blank=True, default='', help_text='Campo legado. Usar interseccion_1 e interseccion_2.', max_length=200, verbose_name='Entre calles (legado)'),
        ),
        migrations.AlterField(
            model_name='subcuadra',
            name='interseccion_1',
            field=models.CharField(blank=True, default='', help_text='Primera calle de la intersección. Ej: 29 - Av. San Martín', max_length=100, verbose_name='Intersección 1'),
        ),
        migrations.AlterField(
            model_name='subcuadra',
            name='interseccion_2',
            field=models.CharField(blank=True, default='', help_text='Segunda calle de la intersección. Ej: 60 - Belgrano', max_length=100, verbose_name='Intersección 2'),
        ),
    ]
